### PR TITLE
Common response generation methods were present throughout Diego.

### PR DESCRIPTION
**Pull request by lwoydziak**
Consolidated these methods here as parallel implementations that can be switched to when convenient.

Signed-off-by: Luke Woydziak <luke.woydziak@emc.com>

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @lwoydziak. Could you please publicize your membership in a GitHub org that has signed a corporate CLA?

**Comment by lwoydziak** [comment]
@ematpl Done

**Comment by luan** [comment]
@lwoydziak we switched from `Ω` some time ago, can you rewrite the tests using `Expect` instead?
Other than that, looks good to me.

**Comment by lwoydziak** [comment]
@luan latest update addresses your comment.

**Comment by luan** [comment]
@lwoydziak sorry I should've been more specific: When doing `Expect` the convention is to use `.To`/`.NotTo` instead of `.Should`/`.ShouldNot` so that it reads better "expect something to something".
The only Gomega constructs that still use `.Should` in our codebases is the `Eventually`/`Consistently`.

Another thing that @ematpl suggested is to pull these helpers into a separate package (still inside this repository) like: `github.com/cloudfoundry-incubator/cf_http/handlers` so we have a specific package for handler helpers.
We'd be happy to pull as-is (well, after you fix the `Should`s) and we can make the separate package afterwards, but will leave it up to you if you want to do both on this PR.

**Comment by ematpl** [comment]
Closing and re-opening to appease Dreddbot.

**Comment by ematpl** [comment]
Hey, @lwoydziak, were you still interested in making those changes that @luan suggested?

Thanks,
Eric

**Comment by lwoydziak** [comment]
Yes, making them now

**Pull request merged**
